name: mvvm_structure
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


  #core
  dio: ^5.3.3
  logger: ^2.0.2+1
  provider: ^6.0.5
  api_cache_manager: ^1.0.2
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  get: ^4.6.5
  google_fonts: ^6.1.0
  rive: ^0.11.17
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  intl: ^0.18.0
  go_router: ^11.1.3
  flutter_linkify: ^6.0.0
  url_launcher: ^6.1.14
  device_preview: ^1.1.0

  # external
  random_color: ^1.0.6-nullsafety
  fraction: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
