name: mvvm_structure
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  #core
  dio: ^5.3.3
  logger: ^2.0.2+1
  provider: ^6.0.5
  api_cache_manager: ^1.0.2
  shared_preferences: ^2.2.2
  get_it: ^7.6.4
  get: ^4.6.5
  rive: ^0.11.17
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  intl: ^0.18.0
  go_router: ^11.1.3
  url_launcher: ^6.1.14
  get_cli: ^1.8.1
  get_storage: ^2.1.1
  animated_theme_switcher: ^2.0.8
  flutter_linkify: ^6.0.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  simple_html_css: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  money_formatter: ^0.0.5
  gradient_icon: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  carousel_indicator: ^1.0.6
  simple_circular_progress_bar: ^1.0.2
  font_awesome_flutter: ^10.6.0
  random_name_generator: ^1.2.0
  animated_toast_list: ^1.0.2
  device_preview: ^1.1.0

  # external
  random_color: ^1.0.6-nullsafety
  fraction: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets: 
    - assets/images/
    - assets/svgs/
    - assets/lottie/
    - assets/fonts/